In [1]:
import numpy as np
import pandas as pd

In [2]:
movies= pd.read_csv("movies_all.csv")
movies.head()

,Movie Title,Year,Score,Director,Synopsis,Cast,Genre,Critic_Consensus,Platform
0,The Baby-Sitters Club,2020,100,"Lucia Aniello, Naia Cucukov, Michael De Luca, ...",A group of friends launch a babysitting busin...,"Sophie Grace, Malia Baker, Momona Tamada, Shay...",NaN,NaN,Netflix
1,Heartstopper,2022,100,"Euros Lyn, Iain Canning, Nicky Earnshaw, Hakan...",Teens Charlie and Nick discover their unlikel...,"Kit Connor, Joe Locke, William Gao, Yasmin Finney",NaN,NaN,Netflix
2,Aggretsuko,2018,100,NaN,Retsuko is a 25-year-old red panda who is gro...,"Kaolip, Komegumi Koiwasaki, Maki Tsuruta",NaN,NaN,Netflix
3,Dash & Lily,2020,100,"Shawn Levy, Josh Barry, Nick Jonas, Brad Silbe...",A whirlwind Christmas romance builds as cynic...,"Austin Abrams, Midori Francis, Dante Brown, Tr...",NaN,NaN,Netflix
4,Arcane: League of Legends,2021,100,"Brandon Beck, Marc Merrill, Nicolo Laurent, Ja...","The origins of two iconic League champions, s...","Hailee Steinfeld, Katie Leung, Kevin Alejandro...",NaN,NaN,Netflix

In [3]:
movies.shape

(2129, 9)

In [4]:
movies.fillna("")

,Movie Title,Year,Score,Director,Synopsis,Cast,Genre,Critic_Consensus,Platform
0,The Baby-Sitters Club,2020,100,"Lucia Aniello, Naia Cucukov, Michael De Luca, ...",A group of friends launch a babysitting busin...,"Sophie Grace, Malia Baker, Momona Tamada, Shay...",,,Netflix
1,Heartstopper,2022,100,"Euros Lyn, Iain Canning, Nicky Earnshaw, Hakan...",Teens Charlie and Nick discover their unlikel...,"Kit Connor, Joe Locke, William Gao, Yasmin Finney",,,Netflix
2,Aggretsuko,2018,100,,Retsuko is a 25-year-old red panda who is gro...,"Kaolip, Komegumi Koiwasaki, Maki Tsuruta",,,Netflix
3,Dash & Lily,2020,100,"Shawn Levy, Josh Barry, Nick Jonas, Brad Silbe...",A whirlwind Christmas romance builds as cynic...,"Austin Abrams, Midori Francis, Dante Brown, Tr...",,,Netflix
4,Arcane: League of Legends,2021,100,"Brandon Beck, Marc Merrill, Nicolo Laurent, Ja...","The origins of two iconic League champions, s...","Hailee Steinfeld, Katie Leung, Kevin Alejandro...",,,Netflix
...,...,...,...,...,...,...,...,...,...
2124,Hard-Boiled,1992,94,John Woo,A cop who loses his partner in a shoot-out wi...,"Chow Yun-Fat, Bowie Lam, Philip Chan, Tony Leu...",,Boasting impactful action as well as surprisin...,Public
2125,The Matrix,1999,88,"Andy Wachowski, Larry Wachowski",Neo (Keanu Reeves) believes that Morpheus (La...,"Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",,"Thanks to the Wachowskis' imaginative vision, ...",Public
2126,Terminator 2: Judgment Day,1991,93,James Cameron,"In this sequel set eleven years after ""The Te...","Arnold Schwarzenegger, Linda Hamilton, Edward ...",,T2 features thrilling action sequences and eye...,Public
2127,Die Hard,1988,94,John McTiernan,New York City policeman John McClane (Bruce W...,"Bruce Willis, Alan Rickman, Bonnie Bedelia, Re...",,Its many imitators (and sequels) have never co...,Public
2128,Mad Max: Fury Road,2015,97,George Miller,"Years after the collapse of civilization, the...","Tom Hardy, Charlize Theron, Nicholas Hoult, Hu...",,With exhilarating action and a surprising amou...,Public

In [5]:
movies['Year']= movies['Year'].map(str)
movies['Score']= movies['Score'].map(str)

In [6]:
# df['d'] = df[['a', 'b', 'c']].fillna('').agg('|'.join, axis=1)
movies['tag']= movies[['Director','Synopsis','Cast','Critic_Consensus','Score','Year']].fillna("").agg(' '.join,axis=1)
movies.head(5)

,Movie Title,Year,Score,Director,Synopsis,Cast,Genre,Critic_Consensus,Platform,tag
0,The Baby-Sitters Club,2020,100,"Lucia Aniello, Naia Cucukov, Michael De Luca, ...",A group of friends launch a babysitting busin...,"Sophie Grace, Malia Baker, Momona Tamada, Shay...",NaN,NaN,Netflix,"Lucia Aniello, Naia Cucukov, Michael De Luca, ..."
1,Heartstopper,2022,100,"Euros Lyn, Iain Canning, Nicky Earnshaw, Hakan...",Teens Charlie and Nick discover their unlikel...,"Kit Connor, Joe Locke, William Gao, Yasmin Finney",NaN,NaN,Netflix,"Euros Lyn, Iain Canning, Nicky Earnshaw, Hakan..."
2,Aggretsuko,2018,100,NaN,Retsuko is a 25-year-old red panda who is gro...,"Kaolip, Komegumi Koiwasaki, Maki Tsuruta",NaN,NaN,Netflix,Retsuko is a 25-year-old red panda who is gr...
3,Dash & Lily,2020,100,"Shawn Levy, Josh Barry, Nick Jonas, Brad Silbe...",A whirlwind Christmas romance builds as cynic...,"Austin Abrams, Midori Francis, Dante Brown, Tr...",NaN,NaN,Netflix,"Shawn Levy, Josh Barry, Nick Jonas, Brad Silbe..."
4,Arcane: League of Legends,2021,100,"Brandon Beck, Marc Merrill, Nicolo Laurent, Ja...","The origins of two iconic League champions, s...","Hailee Steinfeld, Katie Leung, Kevin Alejandro...",NaN,NaN,Netflix,"Brandon Beck, Marc Merrill, Nicolo Laurent, Ja..."

In [7]:
movies = movies.drop(columns= ['Director','Genre','Platform','Synopsis','Cast','Critic_Consensus','Score','Year'])
movies.sample(5)

         Movie Title                                                tag
21          Fanático  Roger Gual  After music artist Quimera dies on...
1963   Monster House  Gil Kenan  No adults believe three youths' (Mi...
110   Whose Streets?  Sabaah Folayan  An account of the Ferguson upr...
1444    The Sopranos  David Chase, Timothy Van Patten, John Patterso...
1885          WALL-E  Andrew Stanton  WALL-E, short for Waste Alloca...

In [8]:
movies['tag'][4]

'Brandon Beck, Marc Merrill, Nicolo Laurent, Jane Chung  The origins of two iconic League champions, set in the utopian Piltover and the oppressed underground of Zaun.... Hailee Steinfeld, Katie Leung, Kevin Alejandro, Jason Spisak  100 2021'

In [9]:
# converting in lowercase
movies['title'] = movies['Movie Title']
movies['tag'] = movies['tag'].str.lower()
movies.sample(5)

,Movie Title,tag,title
517,Ailey,jamila wignot alvin ailey was a trailblazing ...,Ailey
836,One Cut of the Dead,shinichiro ueda real zombies attack a hack di...,One Cut of the Dead
1939,Kung Fu Panda 3,"jennifer yuh nelson, alessandro carloni livin...",Kung Fu Panda 3
690,The Wind,"emma tammi lizzy is a tough, resourceful fron...",The Wind
142,Sorry to Bother You,boots riley in an alternate reality of presen...,Sorry to Bother You

In [10]:
# remove html tags
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [11]:

movies['tag'] = movies['tag'].apply(remove_html_tags)
movies.sample(5)

,Movie Title,tag,title
486,The Night House,david bruckner reeling from the unexpected de...,The Night House
2038,The Guest,adam wingard a string of mysterious deaths le...,The Guest
303,Writing with Fire,"rintu thomas, sushmit ghosh armed with smartp...",Writing with Fire
628,Sweat,magnus von horn beloved fitness influencer sy...,Sweat
1881,Up,"pete docter, bob peterson carl fredricksen (e...",Up

In [12]:
# remove punctuation
import string
exclude = string.punctuation
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))


movies['tag'].apply(remove_punc1)
movies.sample(5)

,Movie Title,tag,title
501,Memoria,apichatpong weerasethakul ever since being st...,Memoria
1866,Finding Nemo,"andrew stanton marlin (albert brooks), a clow...",Finding Nemo
1671,Nomadland,chloé zhao a woman embarks on a journey throu...,Nomadland
1118,Clouds,justin baldoni teenager zach sobiech forms th...,Clouds
74,Hit & Run,"lior raz, avi issacharoff, dawn prestwich, nic...",Hit & Run

In [13]:
from nltk.corpus import stopwords

In [14]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Aryan
[nltk_data]     Chaturvedi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [16]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [17]:
movies['tag'][2]

'  retsuko is a 25-year-old red panda who is growing increasingly frustrated with her job in the accounting department of a... kaolip, komegumi koiwasaki, maki tsuruta  100 2018'

In [18]:
movies['tag']= movies['tag'].apply(remove_stopwords)

In [19]:
movies['tag'][2]

'retsuko   25-year-old red panda   growing increasingly frustrated   job   accounting department  a... kaolip, komegumi koiwasaki, maki tsuruta 100 2018'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')

In [21]:
vector = cv.fit_transform(movies['tag'])
vector.shape

(2129, 17129)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
similarity = cosine_similarity(vector)

In [24]:
similarity.shape

(2129, 2129)

In [25]:
similarity[0]

array([1.        , 0.03857584, 0.04682929, ..., 0.        , 0.        ,
       0.        ])

In [27]:
movies[movies['title']=='The Matrix'].index[0]

2125

In [34]:
def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(movies.iloc[i[0]].title)

In [40]:
recommend('Mad Max: Fury Road')

Mad Max 2: The Road Warrior
Finch
Finch
National Treasure
The Amusement Park